apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-nginx-dep
  name: simple-nginx-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nginx-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-nginx-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
